import { StyleSheet } from "react-native-web";

export const styles = StyleSheet.create({
  row: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    width: "90%",
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "90%",
    paddingTop: 80,
    paddingBottom: 10,
    backgroundColor: "#f0d6e8",
  },
  pokemon: {
    flexDirection: "row",
    alignItems: "start",
    marginBottom: 10,
    width: "100%",
    backgroundColor: "#e4b5d5",
    borderRadius: 5,
    padding: 10,
    gap: 15,
  },
  image: {
    width: 100,
    height: 100,
    marginRight: 0,
    borderRadius: 5,
    backgroundColor: "#e96d7b",
  },
  name: {
    fontSize: 20,
    fontWeight: "bold",
    width: "100%",
    color: "#632c3b",
  },
  input: {
    width: "90%",
    padding: 10,
    borderWidth: 1,
    borderRadius: 5,
    borderWidth: 0,
    backgroundColor: "#d997c5",
    color: "#6e3648",
    fontSize: "1.1em",
  },
  search: {
    width: "100%",
    flex: 1,
    flexDirection: "column",
    gap: 10,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 3,
    position: "fixed",
    top: 0,
    paddingTop: 10,
    paddingBottom: 10,
  },
});
